repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.11
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
      args: ["--diff"]

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.24.1
  hooks:
    - id: validate-pyproject
